### ISSUE TITLE
Märklig /etc/apt/sources.list

### ISSUE THREAD

**Issue by elofu17** [DFRI/dfri-rpi-tor#4]
Öhh...
Efter att jag installerat en DFRI-pi och låtit den boota så ser jag att /etc/apt/sources.list blivit editerad och innehåller enbart en enda rad:
  deb http://deb.torproject.org/torproject.org unstable main

Detta innebär att Debian-operativsystemet inte kan hitta några patchar eller nya paket.

Det känns galet.

**Comment by jn9999** [comment]
Har testat instruktionen i README-filen och systemet som till slut skapades (efter lång väntan och många uppgraderingar) har inte (längre?) det här problemet.
